#Site Settings
theme: jekyll-theme-midnight
title: Adam Tak, Software Developer
email: adam.tak2112@gmail.com
description: A collection of my projects and professional information.
url: adamdtak2112.github.io
twitter_username: yourunclesayshi
